name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Select the environment to deploy"
        type: choice
        required: true
        default: "release"
        options:
          - release
          - staging
          - develop
      service:
        description: "Select services to deploy"
        type: choice
        required: true
        default: "All"
        options:
          - All
          - Frontend
          - MailService
          - UserService
      dry:
        description: "Dry run"
        type: boolean
        required: false
        default: true

jobs:
  release_job:
    name: Release Job
    runs-on: ubuntu-latest

    steps:
      - name: Collect all docker image tags
        id: tags
        run: |
          echo "Release settings: ${{ github.event.inputs.target_branch }}, ${{ github.event.inputs.service }}, ${{ github.event.inputs.dry }}"
          # source ./get-latest-tag.sh some_url_encoded_docker_package SERVICE_XY_TAG
          export SERVICE_XY_TAG=foobar

      - name: Dry run
        if: ${{ github.event.inputs.dry == true }}
        run: |
          echo "Dry run is true, exiting"
          exit 0

      - name: Dynamically create and launch k8s configs
        env:
          SERVICE_XY_TAG: ${{ steps.tags.outputs.SERVICE_XY_TAG }}
        run: |
          echo $SERVICE_XY_TAG
