name: Create Release Auto-Merge Request

on:
  push:
    branches:
      - stage

jobs:
  create-merge-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create pull request and auto-merge to release if possible
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          existing_pr=$(gh pr list --base main --json number,headRefName --jq ".[] | select(.headRefName == \"stage\") | .number")
          if [ -z "$existing_pr" ]; then
            gh pr create -B main -H dev --title 'Merge dev into stage' --body 'Created by Github action'
            gh pr merge --auto --merge
          fi
