name: Create Release Auto-Merge Request

on:
  push:
    branches:
      - stage

jobs:
  create-merge-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create pull request and auto-merge to release if possible
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(gh pr create -B release -H stage --title 'Merge stage into release' --body 'Created by Github action' --json number --jq .number)
          gh pr merge $pr_number --auto --merge
