name: Create Release Auto-Merge Request

on:
  push:
    branches:
      - stage

jobs:
  create-merge-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up env
        run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create pull request and auto-merge to release if possible
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          existing_pr=$(gh pr list --base main --json number,headRefName --jq ".[] | select(.headRefName == \"stage\") | .number")
          if [ -z "$existing_pr" ]; then
            gh pr create -B main -H stage --title 'Merge stage into main' --body 'Created by Github action'
            gh pr merge --auto --merge
            git tag stage-$TIMESTAMP
            git push origin stage-$TIMESTAMP
          fi
